### PR TITLE
fix: update gh-pages readme to have the correct [demo and docs] link

### PR DESCRIPTION
**Pull request by WagnerMoreira**
Hello guys! 

I just discovered this library and I noticed this link was incorrect in the gh pages so the user gets a GitHub 404 page, please consider this pull request.

### CODE REVIEW

**Comment by WagnerMoreira** [comment]
@jquense Hello! :) can you take a look at this when you get a chance?

**Comment by WagnerMoreira** [comment]
up up 😄

**Review by jquense — APPROVED** [review]

**Comment by jquense** [comment]
thanks !

**Comment by WagnerMoreira** [comment]
you're very welcome! thanks for looking at this PR!

**Pull request merged**
