### PR TITLE
feat(DnD): use custom event wrapper component while dragging

### LINKED ISSUE #1864: Use custom eventWrapper component while dragging event (DnD)
#### Do you want to request a _feature_ or report a _bug_?

feature

#### What's the current behavior?

I have a custom eventWrapper component for DnD wrapped Calendar. The component adds some visual styles which must be visible while dragging. When I drag any event DnD hides eventWrapper

#### What's the expected behavior?

The custom eventWrapper component is used while dragging event

### PR DESCRIPTION
**Pull request by nlevchuk**
This change allows to use custom EventWrapper component on preview event

Closes #1864

### CODE REVIEW

**Comment by dhruvgoel92** [comment]
Nice, this is useful.

**Comment by cutterbl** [comment]
@nlevchuk Implemented your changes in #2221 to get around branch conflicts

**Comment by nlevchuk** [comment]
@cutterbl Hello. You made an identical PR (https://github.com/jquense/react-big-calendar/pull/2221) and closed mine. Why? I don't understand your point. Explain me please
I could rebase the main branch to mine one and fix conflicts if they could be

**Comment by cutterbl** [comment]
@nlevchuk There were a large number of unresolved file conflicts with your branch, but your changes were easily replicated on a fresh branch

**Comment by nlevchuk** [comment]
@cutterbl It's two-line changes. I even could create fresh branch from the main one and create new PR if you told me about it. It would save my contribution to the project

**Comment by nlevchuk** [comment]
@cutterbl In modern world it calls "stolen code"

**Comment by cutterbl** [comment]
@nlevchuk I tell you what. I'll pull the changes out, and let you reapply. I really wasn't trying to 'steal' your code, or I wouldn't have posted anything here in the first place. I was just trying to get the changes in. Would that be OK with you?

**Comment by kotchuprik** [comment]
it is a shame.

**Comment by nlevchuk** [comment]
@cutterbl I appreciate your work on the project and thank you for that.

Look at this situation from my side: One of contributors creates a PR with identical changes, merge it to the main branch, close my PR and trying to tell me that what he did is normal. What do you feel if it would happen with you?

>I'll pull the changes out, and let you reapply
I guess it's fair

**Comment by cutterbl** [comment]
@nlevchuk Everyone has a different perspective. I was just trying to move forward a minor change that could obviously be helpful to others, but had sat for four months. But, I see your point of view as well. The changes have been pulled. Please reapply them at your earliest convenience, so that other's may benefit from the change.

**Comment by nlevchuk** [comment]
@cutterbl 
>Everyone has a different perspective. I was just trying to move forward a minor change that could obviously be helpful to others, but had sat for four months

Even if you did your changes from the best intention you played down my work: I spent time creating the issue and the PR.
Anyway, I'm glad that we understood each other. Thank you

I'm going to make the changes right away

**Comment by nlevchuk** [comment]
@cutterbl I've done it https://github.com/jquense/react-big-calendar/pull/2228. Please check this out

**Pull request closed without merging**
