### PR TITLE
fix: issue 2536

### PR DESCRIPTION
**Pull request by forceddd**
This is a commit to fix[ issue 2536](https://github.com/jquense/react-big-calendar/issues/2536) and [2529](https://github.com/jquense/react-big-calendar/issues/2529).

When I was fixing [2529](https://github.com/jquense/react-big-calendar/issues/2529), I declared `slotMetrics` as a global variable, which caused all `DayColumn` instances to use the same instance of `slotMetrics`. This is also the reason why bug [ issue 2536](https://github.com/jquense/react-big-calendar/issues/2536) appears.

In this commit, I only modified the update timing of slotMetrics.Now both issues are resolved!

https://github.com/jquense/react-big-calendar/assets/63057542/756fc1b7-972e-4ef3-bb72-516e068218ac

### CODE REVIEW

**Comment by cutterbl** [comment]
Loading your changes in Storybook, if I go to the onSelectSlot story and begin a selection, it immediately changes it to begin at the beginning of the day up to my selection point.

**Comment by forceddd** [comment]
This is an issue that exists in version 1.11.1 and is not caused by this commit.

**Comment by forceddd** [comment]
> Loading your changes in Storybook, if I go to the onSelectSlot story and begin a selection, it immediately changes it to begin at the beginning of the day up to my selection point.

This is an issue that exists in version 1.11.1 and is not caused by this commit.

**Comment by cutterbl** [comment]
@forceddd You are correct, but it was your previous PR that appears to have introduced this issue in the first place.

**Comment by forceddd** [comment]
This bug should have existed a long time ago. [The issue 2290](https://github.com/jquense/react-big-calendar/issues/2290) seems to be the bug described.
I will try to fix it next week, if I successfully solve this issue, I will create another PR.

**Comment by cutterbl** [comment]
@forceddd Thanks for looking into this. An you are partly right. That issue you pointed out was for dragging up. Now it is also doing it even if dragging down (which was not an issue before your change).

**Comment by forceddd** [comment]
@cutterbl After each `slotMetrics` update, a new `slots` array will be created, but the `_initialSlot` object in `DayColumn` remains unchanged, so `nextSlot` becomes 0:00.
I modified `nextSlot` to handle this case. This video shows the performance after the modification.

https://github.com/jquense/react-big-calendar/assets/63057542/49a17560-6e0f-47c6-bfbb-b93e92cc010e

**Comment by forceddd** [comment]
Is the margin-right here intentionally designed this way? Because when I'm selecting, there is no such spacing, but the rendered result has spacing. This makes me a little confused.
image

**Comment by forceddd** [comment]
@cutterbl Would you please check this PR again? I submitted some new file changes.I think now this PR should be able to solve these related problems.

**Comment by cutterbl** [comment]
@forceddd Another defect (#2565 ) has come up around your changes. Not only is the onSelectSlot no longer returning a slotInfo.action of 'doubleClick', but the onDoubleClickEvent handler function no longer fires either.

**Comment by forceddd** [comment]
> @forceddd Another defect (#2565 ) has come up around your changes. Not only is the onSelectSlot no longer returning a slotInfo.action of 'doubleClick', but the onDoubleClickEvent handler function no longer fires either.

@cutterbl Ok, today I will look at this issue and try to fix it.

**Pull request merged**
