### PR TITLE
Fix for TimeSlots

### PR DESCRIPTION
**Pull request by MincedCutlet**
This small pull request fixes Issue #1442 

This issue occurs due to Pull Request #1204 

In the case where the range of an event is less than the step, this unmodified line will cause the position of the event to be positioned too early.

The bug, as demonstrated [here](https://codesandbox.io/s/react-big-calendar-issue-8mz4i)
When the `step` attribute is set to the minimum time, this fixes the issue, as seen [here](https://codesandbox.io/s/react-big-calendar-issue-i8vf9), but this forces a change in UI, which is not desirable.

While this current fix resolves the issue to correctly push any events past the calendar height back within, it has the unfortunate side effect of utilizing the `step` attribute to determine the height. For an arbitrarily large step, this will push it to the top of the large step block.

I welcome any feedback prior to modifying the tests.

### CODE REVIEW

**Comment by stianeikeland** [comment]
I can confirm that this PR solves events being offset, as reported in #1396

**Comment by antondomratchev** [comment]
@MincedCutlet Can you please update the failing tests. I think the assertions should be `.toBeGreaterThanOrEqual` to pass but I am not sure if that's the desired assertion.

**Comment by Npervic** [comment]
Is this getting anywhere? I'm having multiple problems displaying events...

**Comment by stianeikeland** [comment]
Any chance of merging this?
It fixes this offset issue:

**Comment by antondomratchev** [comment]
@stianeikeland Can you update the broken tests so the merge can happen. See here for details: https://travis-ci.org/intljusticemission/react-big-calendar/builds/588275219?utm_source=github_status&utm_medium=notification

**Comment by mattmattvanvoorst** [comment]
Any chance of this being merged in the near feature?

**Comment by jquense** [comment]
need to see if tests pass, i can't push to this branch and i can't restart manually.

**Pull request merged**
