### PR TITLE
chore(vers): upgrade prop-types

### PR DESCRIPTION
**Pull request by Malvolio**
In response to [Issue 1651](https://github.com/jquense/react-big-calendar/issues/1651) in the original repo.

### CODE REVIEW

**Comment by Malvolio** [comment]
@TrySound — more than welcome, but can you do the merge?  I cannot.

**Comment by TrySound** [comment]
I can merge but I can't publish anyway.

**Comment by jquense** [comment]
publishes are automatic for semantic titles of the type `feat:` or `fix:`

**Comment by Malvolio** [comment]
Hahaha, if I had known that, I would have marked it `fix:`.  Is there any easy bug you want fixed?  I'll do it over the weekend and this can ride its coattails.

**Pull request merged**
