### PR TITLE
fix: render resources under each day in header column

### PR DESCRIPTION
**Pull request by fs-nathan**
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Always follow the [contribution guidelines](https://github.com/jquense/react-big-calendar/blob/master/CONTRIBUTING.md) when submitting a pull request.

### CODE REVIEW

**Comment by cutterbl** [comment]
While this initially appears really good, it completely changes the current default functionality, making it a breaking change. This would be better served by a new prop, with refactor to use as an alternative view, providing both the default (current) and new.

**Comment by almeidapaulooliveira** [comment]
To make it simple and be able to merge, what if we have a prop (exposed in `Calendar`) to render the week on default and this? Will avoid the work of refactoring to an alternative view and quickly release the new feature. 

Wdyt?

**Comment by cutterbl** [comment]
@almeidapaulooliveira It's not about having the week on default (that's already a given). It's the difference between grouping days under resources (current display) as opposed to resources under days. I agree that a top level prop (`resourceGroupingLayout`?) allowing to switch is good, but that would require conditional logic in TimeGrid for both the grouping logic, and application of flexbox wrapper components.

**Comment by almeidapaulooliveira** [comment]
@cutterbl I created a new [PR](https://github.com/jquense/react-big-calendar/pull/2652), that implements what we discussed. Looking forward for your review.

**Comment by cutterbl** [comment]
This has been addressed in a new PR with a new prop

**Pull request closed without merging**
