### PR TITLE
1649 multiple resources

### LINKED ISSUE #1649: Multiple resources per event
Hi

This is an awesome component, thanks! I'd like to be able to assign multiple resources to a single event and then render this in the resource view.

In my events object, I have an array of ids for each resource linked. This seems to prevent the event from rendering. If I change this to a single ID string it works fine.

Has anyone managed to make this work?

Cheers
Alex

### PR DESCRIPTION
**Pull request by jimhlad**
Continued from here (ported the functionality and made some adjustments): https://github.com/jquense/react-big-calendar/pull/1724 

Per #1649 , this adds support for events linked to multiple resources.

The example code has been updated to demonstrate two possible drag and drop behaviours:

1. Copy - By dragging an event into a different resource lane, the event gets assigned to both resources.
2. Move - By dragging an event into a different resource lane, the event is removed from the source resource and added to the target resource.

Please see `stories/demos/exampleCode/dndresource.js` for an example.

Fixes #1649

### CODE REVIEW

**Comment by jimhlad** [comment]
@cutterbl Let me know if anything else is needed here.

Happy to make any changes needed to get this integrated.

**Comment by cutterbl** [comment]
@jimhlad I haven't had time to thoroughly review the changes yet, but I did notice that there weren't any changes to the stories to explain the change in behavior.

**Comment by cutterbl** [comment]
@jimhlad That's part of it, but also some explanation in the documentation. Maybe something in the [resources prop documentation](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--resources)?

**Comment by cutterbl** [comment]
@jimhlad Can you please update your branch with latest changes to 'master' for testing please? As well as add some documentation? Think this would be a great feature.

**Comment by basstager** [comment]
@cutterbl As this is quite a nice feature, desired by our team as well I opened a new PR (https://github.com/jquense/react-big-calendar/pull/2405) with an update from master and some minor documentation updates.

**Pull request closed without merging**
