### PR TITLE
feat(time-grid): allow consumer to set allDayMaxRows (#2386)

### PR DESCRIPTION
**Pull request by fornesarturo**
* Addresses #2386 
* Currently react-big-calendar is not limiting the amount of events in the All day row displayed in Week and Day view, if this row grows it may also cover the events and prevent the user from seeing their normal events.

### In this commit:
* Add support for displaying Show more text in TimeGrid views via allDayMaxRows prop.
* Prevent Background cells from capturing click on show more button.

### CODE REVIEW

**Comment by cutterbl** [comment]
@fornesarturo First pass looks like it might be good, but we would need a story in storybook for the new prop, and showcasing how it works.

**Comment by fornesarturo** [comment]
@cutterbl added story for the new prop and updated the API mdx to include it as well

**Comment by cutterbl** [comment]
@fornesarturo Thanks. I'll try to load this up and take a look over the weekend maybe.

**Comment by fornesarturo** [comment]
Anything missing to have this merged?

**Comment by cutterbl** [comment]
@fornesarturo A deeper look at the failing 'show more' functionality shows that the `onShowMore` prop isn't getting passed in to the `TimeGrid` in the `Day`, `Week` or `WorkWeek` components, so that prop isn't available to call. In our next version we'll handle these things with context, but for now these props are manually passed down the component tree.

**Comment by fornesarturo** [comment]
@cutterbl I see that first part as the usual behavior for the `maxRows` prop in the `DateContentRow` component and the `getSlotMetrics` function where `maxRows` includes the show more button row, I could make it so when passing the prop down to `DateContentRow` it is handled as `allDayMaxRows - 1`, maybe change the name of the prop to `allDayMaxEvents` to make it clear. For null I can add the if else with `Infinity`, to handle null as undefined.

On an implementation using react-big-calendar with these changes I am getting a call to the onShowMore function, since I'm working off of that call it worked for my case. I see that what the Month view currently does is it defines the overlay there, it's not something central, I could add the functionality following Month view's approach, per the commits that seems like an intentional exception:

```
handleShowMore = (events, date, cell, slot, target) => {
    const {
      popup,
      onDrillDown,
      onShowMore,
      getDrilldownView,
      doShowMoreDrillDown,
    } = this.props
    //cancel any pending selections so only the event click goes through.
    this.clearSelection()

    if (popup) {
      let position = getPosition(cell, this.containerRef.current)

      this.setState({
        overlay: { date, events, position, target },
      })
    } else if (doShowMoreDrillDown) {
      notify(onDrillDown, [date, getDrilldownView(date) || views.DAY])
    }

    notify(onShowMore, [events, date, slot])
  }
```

I see the differences in notifying the onShowMore prop here where it sends the parameters as an array, so that I can change quickly.

Let me know your thoughts.

**Comment by fornesarturo** [comment]
Result of adding the Month view code to TimeGrid:

image

**Comment by fornesarturo** [comment]
@cutterbl  Added changes to handle overlay and update the `onShowMore` prop `notify` call. Waiting on any comment to change handling of the limited rows in `allDayMaxRows` (subtract one before sending to `maxRows` to not include the Show more button row in the count) or keep as is (include Show more button row in the count).

**Comment by cutterbl** [comment]
@fornesarturo I loaded your changes and brought up storybook. Still not getting the popup with the `popup` prop in the `allDayMaxRows` story...

**Comment by cutterbl** [comment]
@fornesarturo Still not getting the popup, but I do see multiple console warnings
> Warning: Failed prop type: The prop `min` is marked as required in `Week`, but its value is `undefined`.
> Warning: Failed prop type: The prop `max` is marked as required in `Week`, but its value is `undefined`.
> Warning: Failed prop type: The prop `scrollToTime` is marked as required in `Week`, but its value is `undefined`.

**Comment by fornesarturo** [comment]
@cutterbl Hi, just updated to correctly displayed the popup, and fixed propTypes to make sense with settings across the repo.

**Comment by fornesarturo** [comment]
@cutterbl row count is fixed now and displays the number of rows for events specified.

**Pull request merged**
