### PR TITLE
fix: scrollToTime does not work properly, when min specified

### PR DESCRIPTION
**Pull request by hiroro-work**
Fixed a bug that prevented scrollToTime does not working properly,  when min specified.

### CODE REVIEW

**Comment by gdantas-laon** [comment]
pls accept this PR!!

**Comment by Poky85** [comment]
@gdantas-laon Until fix is merged this works for me:

```tsx
import * as React from 'react';
import { Calendar } from 'react-big-calendar';

const defaultMin = new Date(1972, 0, 1, 0, 0, 0, 0);

const normalizeTime = (time: Date) => {
  const normalized = new Date(time);
  normalized.setFullYear(1972, 0, 1);
  return normalized;
};

const getFixedScrollToTime = (scrollToTime: Date, min: Date) => {
  const time = normalizeTime(scrollToTime);
  const minimum = normalizeTime(min);
  const shiftMilliseconds = minimum.getTime() - defaultMin.getTime();

  return new Date(Math.max(defaultMin.getTime(), time.getTime() - shiftMilliseconds));
};

const MyCalendar: React.FunctionComponent = () => {
  const min = new Date(1972, 0, 1, 7, 0);
  const max = new Date(1972, 0, 1, 20, 0);
  const scrollToTime = new Date(1970, 0, 1, 12, 0);

  return (
    <Calendar events={[]} min={min} max={max} scrollToTime={getFixedScrollToTime(scrollToTime)} />
  );
};

```

**Comment by cutterbl** [comment]
Can you update your branch with latest from master? Then I can test your changes.

**Comment by hiroro-work** [comment]
@cutterbl Updated!

**Pull request merged**
