### PR TITLE
fix: no-overlap layout algorithm

### LINKED ISSUE #2240: no-overlap layout algorithm issue
### Check that this is really a bug

- [X] I confirm

### Bug description

`no-overlap` algorithm does not work correctly.

### Steps to reproduce:

1. Open https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/examples--example-3
2. Select Day view.
3. Create event from 12:00 AM to 1:00 AM.
4. Create another event from 1:00 AM to 1:30 AM.

### Current effect
e1

### Expected effect

Both slots from the example should be full wide.

### react-big-calendar version

1.5.0

### React version

17.0.2

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

### PR DESCRIPTION
**Pull request by lukbak**
Closes #2240 

### We have 3 cases to handle:
cases

### Current effect
e1
e3

### Effect after fix
e2
e4

### CODE REVIEW

**Comment by blugnomeXD** [comment]
I am testing this, and doesn't work. Could you provide thecode that your used for this test ?

**Comment by lukbak** [comment]
@blugnomeXD just reproduce the issue from #2240. Please remember that this code is related to no-overlap algorithm.

**Comment by blugnomeXD** [comment]
@lukbak  Thanks for your answer. Yes i am using no-overlap because i have the same issue that you reported.  Is enought to pass the prop dayLayoutAlgorithm='no-overlap' or i need something else?
Thanks

**Comment by lukbak** [comment]
Hello @cutterbl. I would like to ask when we can expect this change? Do you have any comments?

**Comment by lukbak** [comment]
@cutterbl @dhruvgoel92 Please take a look.

**Pull request merged**
